# ***Food Classification Using K-Nearest Neighbors (KNN) Algorithm***

---

In [1]:
# Import the libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    classification_report
)

In [2]:
#Creating the dataset

dataset = {
    "ingrediant" : ["apple", "bacon", "banana", "carrot", "celery", "cheese", "grapes", "greenbeans", "nuts", "orange"],
    "sweetness" : [10, 1, 10, 7, 3, 1, 8, 3, 3, 7],
    "crunchiness" : [9, 4, 1, 10, 10, 1, 5, 7, 6, 3],
    "food type" : ["fruit", "protien", "fruit", "vegie", "vegie", "protien", "fruit", "vegie", "protien", "fruit"]
}

In [3]:
# Create the alias of Pandas

df = pd.DataFrame(dataset)
df.head(10)

   ingrediant  sweetness  crunchiness food type
0       apple         10            9     fruit
1       bacon          1            4   protien
2      banana         10            1     fruit
3      carrot          7           10     vegie
4      celery          3           10     vegie
5      cheese          1            1   protien
6      grapes          8            5     fruit
7  greenbeans          3            7     vegie
8        nuts          3            6   protien
9      orange          7            3     fruit

In [4]:
# df.describe() generates summary statistics for numerical columns in a DataFrame, such as count, mean, standard deviation, minimum, and maximum.
# It helps quickly understand the data's distribution and central tendency.

df.describe()

       sweetness  crunchiness
count  10.000000    10.000000
mean    5.300000     5.600000
std     3.497618     3.405877
min     1.000000     1.000000
25%     3.000000     3.250000
50%     5.000000     5.500000
75%     7.750000     8.500000
max    10.000000    10.000000

In [5]:
# df.shape displays the number of rows and columns in the dataset.
# df.columns lists all column names, while df.info() shows column data types, non-null counts, and memory usage.

print("Dataset Shape:", df.shape)

print("\nColumns:\n")
print(df.columns)

print("\nDataset Information:\n")
print(df.info())

Dataset Shape: (10, 4)

Columns:

Index(['ingrediant', 'sweetness', 'crunchiness', 'food type'], dtype='object')

Dataset Information:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ingrediant   10 non-null     object
 1   sweetness    10 non-null     int64
 2   crunchiness  10 non-null     int64
 3   food type    10 non-null     object
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes
None

In [6]:
# df.isnull().sum() counts the number of missing (NaN or null) values in each column of the DataFrame.
# It helps identify columns with missing data that may require cleaning or preprocessing.

print(df.isnull().sum())

ingrediant     0
sweetness      0
crunchiness    0
food type      0
dtype: int64

In [7]:
# selects the input features & the target variable

X = df[['sweetness', 'crunchiness']]
y = df['food type']

In [8]:
# defines the tomato's features, where sweetness is 6 and crunchiness is 4.

tomato = [[6, 4]]

In [9]:
# KNN classification model that uses the 4 nearest neighbors to make predictions.

model = KNeighborsClassifier(
    n_neighbors=4
    )

In [10]:
# trains the KNN model using the input features (X) and their corresponding target labels (y).

model.fit(X, y)

KNeighborsClassifier(n_neighbors=4)

In [11]:
# predicts the food type of the tomato

y_pred = model.predict(tomato)

print(y_pred)

['fruit']

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(